### ISSUE TITLE
Separation French texts into a separate file

### ISSUE THREAD

**Issue by swiktor** [osajw/terr-helper#1]
Hello,
Would it be possible for you to extract the French texts into a separate file? I would like to translate into Polish, but if I do it now, any update will overwrite it.

Best wishes
Szymon

**Comment by osajw** [comment]
Hello Szymon !
Yes, that would be a nice feature to have! I will do it as soon as possible :)

**Comment by swiktor** [comment]
Thank You so much. I will be waiting :)

**Comment by osajw** [comment]
Hello, you can now add your translations to the application!
In [/resources/js/lang](https://github.com/osajw/terr-helper/tree/main/resources/js/lang) add a `pl.js` file.
See ["how-can-i-translate-into-another-language"](https://github.com/osajw/terr-helper#how-can-i-translate-into-another-language) 😉
